const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
const FAHRENHEIT = "FAHRENHEIT";
const FETCH_DATA = "FETCH_DATA";
const CELCIUS = "CELCIUS";

export { GET_CURRENT_LOCATION, FAHRENHEIT, CELCIUS, FETCH_DATA };
