const CURRENT_DATA_BY_CITY = "CURRENT_DATA_BY_CITY";
const FORECAST_BY_CITY = "FORECAST_BY_CITY";
const FORECAST = "FORECAST";
const CURRENT_DATA = "CURRENT_DATA";
const FAHRENHEIT = "FAHRENHEIT";
const FETCH_DATA = "FETCH_DATA";
const CELCIUS = "CELCIUS";
const DATA_START = "DATA_START";

export {
    CURRENT_DATA_BY_CITY,
    FORECAST_BY_CITY,
    CURRENT_DATA,
    FAHRENHEIT,
    FETCH_DATA,
    DATA_START,
    FORECAST,
    CELCIUS,
};
