const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
const FORECAST = "FORECAST";
const CURRENT_DATA = "CURRENT_DATA";
const FAHRENHEIT = "FAHRENHEIT";
const FETCH_DATA = "FETCH_DATA";
const CELCIUS = "CELCIUS";
const DATA_START = "DATA_START";

export {
    GET_CURRENT_LOCATION,
    CURRENT_DATA,
    FAHRENHEIT,
    FETCH_DATA,
    DATA_START,
    FORECAST,
    CELCIUS,
};
